import { FaLinkedin, FaSkype } from "react-icons/fa6";
import {
  SiGithub,
  SiGitbook,
  SiMedium,
  SiOrcid,
  SiBluesky,
  SiThreads,
  SiDiscord,
  SiDribbble,
  SiBehance,
  SiStackoverflow,
  SiGitlab,
  SiQuora,
  SiFacebook,
  SiInstagram,
  SiWechat,
  SiHuggingface,
  SiKaggle,
  SiYoutube,
  SiTiktok,
  SiSignal,
  SiTelegram,
  SiX,
} from "react-icons/si";
import {
  FiGlobe,
  FiFlag,
  FiCalendar,
  FiShield,
  FiHome,
  FiDollarSign,
  FiSmartphone,
  FiTruck,
  FiLock,
  FiHeart,
  FiActivity,
  FiInfo,
} from "react-icons/fi";

export const EXTRA_ICONS = {
  linkedin: FaLinkedin,
  website: FiGlobe,
  portfolio: FiGlobe,
  github: SiGithub,
  gitbook: SiGitbook,
  medium: SiMedium,
  orcid: SiOrcid,
  skype: FaSkype,
  bluesky: SiBluesky,
  threads: SiThreads,
  x: SiX,
  discord: SiDiscord,
  dribbble: SiDribbble,
  behance: SiBehance,
  stackoverflow: SiStackoverflow,
  gitlab: SiGitlab,
  quora: SiQuora,
  facebook: SiFacebook,
  instagram: SiInstagram,
  wechat: SiWechat,
  huggingface: SiHuggingface,
  kaggle: SiKaggle,
  youtube: SiYoutube,
  tiktok: SiTiktok,
  signal: SiSignal,
  telegram: SiTelegram,

  nationality: FiFlag,
  dob: FiCalendar,
  visa: FiShield,
  passport: FiShield,
  availability: FiCalendar,
  genderPronoun: FiInfo,
  disability: FiActivity,
  workMode: FiHome,
  relocation: FiTruck,
  expectedSalary: FiDollarSign,
  secondPhone: FiSmartphone,
  drivingLicense: FiTruck,
  securityClearance: FiLock,
  maritalStatus: FiHeart,
  militaryService: FiShield,
  smoking: FiActivity,
  height: FiActivity,
  weight: FiActivity,
};

// fallback icon for any key not listed above
export const DefaultExtraIcon = FiInfo;
