export const TEMPLATES = [
  {
    id: 1,
    name: "Nova",
    cat: "Professional",
    colors: ["#2563eb", "#1e293b", "#f8fafc"],
    style: "classic",
    badge: "popular",
  },
  {
    id: 2,
    name: "Slate",
    cat: "Minimal",
    colors: ["#0f172a", "#334155", "#f8fafc"],
    style: "minimal",
    badge: null,
  },
  {
    id: 3,
    name: "Pulse",
    cat: "Creative",
    colors: ["#7c3aed", "#1e293b", "#ffffff"],
    style: "sidebar",
    badge: "new",
  },
  {
    id: 4,
    name: "Frost",
    cat: "Minimal",
    colors: ["#0ea5e9", "#f0f9ff", "#0f172a"],
    style: "clean",
    badge: null,
  },
  {
    id: 5,
    name: "Ember",
    cat: "Creative",
    colors: ["#ea580c", "#1e293b", "#fff7ed"],
    style: "bold",
    badge: null,
  },
  {
    id: 6,
    name: "Ivory",
    cat: "Professional",
    colors: ["#1e293b", "#f1f5f9", "#ffffff"],
    style: "classic",
    badge: "popular",
  },
  {
    id: 7,
    name: "Sage",
    cat: "Minimal",
    colors: ["#16a34a", "#f0fdf4", "#0f172a"],
    style: "clean",
    badge: null,
  },
  {
    id: 8,
    name: "Crimson",
    cat: "Creative",
    colors: ["#dc2626", "#0f172a", "#ffffff"],
    style: "bold",
    badge: "new",
  },
  {
    id: 9,
    name: "Zenith",
    cat: "Professional",
    colors: ["#2563eb", "#eff6ff", "#0f172a"],
    style: "sidebar",
    badge: null,
  },
  {
    id: 10,
    name: "Onyx",
    cat: "Executive",
    colors: ["#0f172a", "#1e293b", "#94a3b8"],
    style: "dark",
    badge: null,
  },
  {
    id: 11,
    name: "Coral",
    cat: "Creative",
    colors: ["#f43f5e", "#fff1f2", "#0f172a"],
    style: "clean",
    badge: null,
  },
  {
    id: 12,
    name: "Architect",
    cat: "Executive",
    colors: ["#1e293b", "#334155", "#f8fafc"],
    style: "twoCol",
    badge: "popular",
  },
  {
    id: 13,
    name: "Breeze",
    cat: "Minimal",
    colors: ["#0ea5e9", "#ffffff", "#0f172a"],
    style: "minimal",
    badge: null,
  },
  {
    id: 14,
    name: "Dusk",
    cat: "Creative",
    colors: ["#8b5cf6", "#4c1d95", "#ede9fe"],
    style: "sidebar",
    badge: null,
  },
  {
    id: 15,
    name: "Atlas",
    cat: "Executive",
    colors: ["#0f172a", "#2563eb", "#ffffff"],
    style: "bold",
    badge: "new",
  },
];

export const CATEGORIES = [
  { label: "All templates", count: 15 },
  { label: "Professional", count: 4 },
  { label: "Minimal", count: 4 },
  { label: "Creative", count: 4 },
  { label: "Executive", count: 3 },
];

export const COLOR_FILTERS = [
  { label: "Blue", hex: "#2563eb" },
  { label: "Dark", hex: "#0f172a" },
  { label: "Green", hex: "#16a34a" },
  { label: "Purple", hex: "#7c3aed" },
  { label: "Red", hex: "#dc2626" },
];

export const FEATURE_FILTERS = [
  "ATS optimized",
  "Photo slot",
  "Two columns",
  "Icons support",
];
