export const plans = [
  {
    icon: "🌱",
    iconBg: "linear-gradient(135deg, #d1fae5, #a7f3d0)",
    name: "Starter",
    desc: "Perfect for individuals just getting started.",
    monthlyPrice: 0,
    yearlyPrice: 0,
    priceNote: "No credit card required",
    featured: false,
    btnLabel: "Get started free",
    btnStyle: "default",
    features: [
      "Up to 3 projects",
      "5 GB storage",
      "Basic analytics",
      "Email support",
      "API access (limited)",
    ],
  },
  {
    icon: "⚡",
    iconBg: "linear-gradient(135deg, #1e3a5f, #2563eb)",
    name: "Pro",
    desc: "Everything you need to grow and scale fast.",
    monthlyPrice: 29,
    yearlyPrice: 19,
    priceNote: "Per seat / month",
    featured: true,
    btnLabel: "Start free trial",
    btnStyle: "featured",
    features: [
      "Unlimited projects",
      "100 GB storage",
      "Advanced analytics",
      "Priority support",
      "Full API access",
      "Custom integrations",
      "Team collaboration",
    ],
  },
  {
    icon: "🏢",
    iconBg: "linear-gradient(135deg, #f3f4f6, #e5e7eb)",
    name: "Enterprise",
    desc: "Tailored solutions for large organizations.",
    monthlyPrice: 99,
    yearlyPrice: 69,
    priceNote: "Per seat / month",
    featured: false,
    btnLabel: "Contact sales",
    btnStyle: "enterprise",
    features: [
      "Everything in Pro",
      "Unlimited storage",
      "Custom reporting",
      "Dedicated account manager",
      "SSO & SAML",
      "SLA guarantee",
      "On-premise option",
    ],
  },
];
